name: Lint Code Base
on: 
  push

jobs:
  API-Testing:
    runs-on: ubuntu-latest

    steps:
     
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Newman
        run: npm install -g newman
      - name: Run postman collection
        run: npm run api-testing 
        
      - name: Install Allure
        run: npm install testcafe-reporter-allure
      - name: Path Allure
        run: npm run test-allure
      - name: Visual Report Allure
        run: npm run visual-report-allure

      - name: Install Eslint
        run: npm install eslint
      - name: Init Eslint
        run: npx eslint --init
    
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
